apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "golinks"
  description: "GO Links Docs"
  annotations:
    github.com/project-slug: splunk-backstage/golinks
    backstage.io/techdocs-ref: url:https://github.com/splunk-backstage/golinks
spec:
  type: documentation
  lifecycle: experimental
  owner: "tonytam-splunk"
